export const COLORS = {
  ROLLPE_MAIN: "#FF5656",
  ROLLPE_PRIMARY: "#FFFFFF",
  ROLLPE_SECONDARY: "#181818",
  ROLLPE_GRAY: "#AAAAAA",
  ROLLPE_SECTION_BACKGROUND: "#F4F4F4",
  ROLLPE_STATUS_ACTIVE: "#EF3C3C",
};

